-- This file was generated by pg-forward
-- Notes:
--   1) Do not remove the migration id tag in the head section, although it can be changed to any GUID
--   2) Do not remove or alter the dbVersion tag in the head section    
--   3) Do not write idempotent migration statements (e.g. CREATE TABLE IF NOT EXISTS...)
--   4) Rollback statements should be written to reverse the effects of migrations in reverse order
--   5) Statements can be separated by the [go] directive, but not required to be

-- [head]
-- [id: $(migrationId)]
-- [dbVersion: $(dbVersion)]
-- [metadata.author: $(author)]$(metadata)    
-- [/head]

-- [up]
-- TODO: Write migration statements
-- [/up]

-- [down]
-- TODO: Write rollback statements
-- [/down]
