//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbForward.Engine.Help {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DbForward.Engine.Help.HelpResources", typeof(HelpResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string root {
            get {
                return ResourceManager.GetString("root", resourceCulture);
            }
        }
        
        internal static string globaloptions_loglevel {
            get {
                return ResourceManager.GetString("globaloptions.loglevel", resourceCulture);
            }
        }
        
        internal static string globaloptions_environmentfile {
            get {
                return ResourceManager.GetString("globaloptions.environmentfile", resourceCulture);
            }
        }
        
        internal static string globaloptions_noterminal {
            get {
                return ResourceManager.GetString("globaloptions.noterminal", resourceCulture);
            }
        }
        
        internal static string root_version {
            get {
                return ResourceManager.GetString("root version", resourceCulture);
            }
        }
        
        internal static string connectionoptions_connectionstring {
            get {
                return ResourceManager.GetString("connectionoptions.connectionstring", resourceCulture);
            }
        }
        
        internal static string connectionoptions_host {
            get {
                return ResourceManager.GetString("connectionoptions.host", resourceCulture);
            }
        }
        
        internal static string connectionoptions_port {
            get {
                return ResourceManager.GetString("connectionoptions.port", resourceCulture);
            }
        }
        
        internal static string connectionoptions_database {
            get {
                return ResourceManager.GetString("connectionoptions.database", resourceCulture);
            }
        }
        
        internal static string connectionoptions_userid {
            get {
                return ResourceManager.GetString("connectionoptions.userid", resourceCulture);
            }
        }
        
        internal static string connectionoptions_password {
            get {
                return ResourceManager.GetString("connectionoptions.password", resourceCulture);
            }
        }
        
        internal static string connectionoptions_properties {
            get {
                return ResourceManager.GetString("connectionoptions.properties", resourceCulture);
            }
        }
        
        internal static string newenvironmentoptions_outputfile {
            get {
                return ResourceManager.GetString("newenvironmentoptions.outputfile", resourceCulture);
            }
        }
        
        internal static string newenvironmentoptions_overwrite {
            get {
                return ResourceManager.GetString("newenvironmentoptions.overwrite", resourceCulture);
            }
        }
        
        internal static string root_env_new_file {
            get {
                return ResourceManager.GetString("root env new-file", resourceCulture);
            }
        }
        
        internal static string newenvironmentoptions_edit {
            get {
                return ResourceManager.GetString("newenvironmentoptions.edit", resourceCulture);
            }
        }
        
        internal static string root_env {
            get {
                return ResourceManager.GetString("root env", resourceCulture);
            }
        }
        
        internal static string root_env_vars {
            get {
                return ResourceManager.GetString("root env vars", resourceCulture);
            }
        }
    }
}
