-- This file was generated by pg-forward
-- Notes:
--   1) Do not remove the migration id tag in the head section, although it can be changed to any GUID
--   2) Do not remove or alter the dbVersion tag in the head section    
--   3) Do not write idempotent migration statements (e.g. CREATE TABLE IF NOT EXISTS...)
--   4) Rollback statements should be written to reverse the effects of migrations in reverse order
--   5) Statements can be separated by the [go] directive, but not required to be

-- [head]
-- [id: 55265a84-c76b-4d9e-8aab-f6db53ac7ba5]
-- [dbVersion: 20241115-195839]
-- [metadata.author: dan]    
-- [/head]

-- [up]
create table sample.addresstype(
  typename text not null,
  constraint pk__addresstype primary key(typename)
);
create table sample.address(
  id uuid not null,
  typename text not null,
  street1 text not null,
  street2 text null,
  buildingnum text null,
  city text not null,
  state text not null,
  postalcode text not null,
  constraint pk__address primary key(id),
  constraint fk__address_addresstype foreign key(typename) references sample.addresstype(typename)
)
-- [go]
insert into sample.addresstype(typename) select 'Residential';
insert into sample.addresstype(typename) select 'Commercial';
insert into sample.addresstype(typename) select 'Government';
-- [/up]

-- [down]
drop table sample.address;
drop table sample.addresstype;
-- [/down]

