-- This file was generated by pg-forward
-- Notes:
--   1) Do not remove the migration id tag in the head section, although it can be changed to any GUID
--   2) Do not remove or alter the dbVersion tag in the head section    
--   3) Do not write idempotent migration statements (e.g. CREATE TABLE IF NOT EXISTS...)
--   4) Rollback statements should be written to reverse the effects of migrations in reverse order
--   5) Statements can be separated by the [go] directive, but not required to be

-- [head]
-- [id: ac87c31f-fd32-4cd1-a1ee-f60426b66b5b]
-- [dbVersion: 20241115-203131]
-- [metadata.author: dan]    
-- [/head]

-- [up]
create table sample.phonetype(
    typename text not null,
    constraint pk__phonetype primary key(typename)
);
-- [go]
insert into sample.phonetype(typename) select 'Home';
insert into sample.phonetype(typename) select 'Office';
insert into sample.phonetype(typename) select 'Mobile';
-- [go]
create table sample.account(
    id uuid not null,
    firstname text not null,
    lastname text not null,
    emailaddress text not null,
    photo bytea null,
    constraint pk__account primary key(id)
);
-- [go]
create table sample.phonenumber(
    id uuid not null,
    accountid uuid not null,
    typename text not null,
    countrycode int not null,
    phonenumber text not null,
    constraint pk__phonenumber primary key(id),
    constraint fk__phonenumber_account foreign key(typename) references sample.phonetype(typename),
    constraint uq__countrycode_phonenumber unique(accountid, countrycode, phonenumber)
);
-- [/up]

-- [down]
drop table if exists sample.phonenumber;
drop table if exists sample.account;
drop table if exists sample.phonetype;
-- [/down]

