-- This file was generated by pg-forward
-- Notes:
--   1) Do not remove the migration id tag in the head section, although it can be changed to any GUID
--   2) Do not remove or alter the dbVersion tag in the head section    
--   3) Do not write idempotent migration statements (e.g. CREATE TABLE IF NOT EXISTS...)
--   4) Rollback statements should be written to reverse the effects of migrations in reverse order
--   5) Statements can be separated by the [go] directive, but not required to be

-- [head]
-- [id: d5de9297-b2d1-49c6-a634-18e8113255d5]
-- [dbVersion: 2024-11-14T16:11:07]
-- [metadata.author: testy]    
-- [/head]

-- [up]
create schema core;
-- [/up]

-- [down]
drop schema if exists core;
-- [/down]

