-- This file was generated by pg-forward
-- Notes:
--   1) Do not remove the migration id tag in the head section, although it can be changed to any GUID
--   2) Do not remove or alter the dbVersion tag in the head section    
--   3) Do not write idempotent migration statements (e.g. CREATE TABLE IF NOT EXISTS...)
--   4) Rollback statements should be written to reverse the effects of migrations in reverse order
--   5) Statements can be separated by the [go] directive, but not required to be

-- [head]
-- [id: 50f1f228-9707-4e10-8add-520a1a910c99]
-- [dbVersion: 2024-11-14T16:11:08]
-- [metadata.author: testy]   
-- [metadata.task: CE_10029] 
-- [/head]

-- [up]
create table core.account(
    id uuid not null,
    emailaddress text not null,
    login text not null,
    passhash text not null,
    primary key(id)
);
-- [/up]

-- [down]
drop table if exists core.account;
-- [/down]
